from routes.login import login_bp
from routes.registro import registro_bp
from routes.cocina_produccion import cocina_produccion_bp
from routes.cocina_pedidos import cocina_pedidos_bp
from routes.cliente import cliente_bp
from routes.proveedor import proveedor_bp
from routes.economia import economia_bp
from routes.detalle_produccion import detalle_produccion_bp
from routes.recetas import recetas_bp
from routes.proceso_venta import venta_bp
from routes.resumen_venta import resumen_venta_bp
from routes.usuario import usuario_bp
from routes.route_galleta import route_galleta
from routes.insumos import insumos_bp
from routes.cocina_insumos import cocina_insumos_bp
from routes.galleta import galleta_bp
from routes.resumen_venta import resumen_venta_bp
from routes.ventas_pedidos import pedidos_ventas_bp
from routes.compra_insumos import compra_insumo_admin_bp
