from routes.login import login_bp
from routes.registro import registro_bp
from routes.cocina_produccion import cocina_produccion_bp
from routes.cocina_pedidos import cocina_pedidos_bp
from routes.cliente import cliente_bp
from routes.proveedor import proveedor_bp
from routes.cliente import cliente_bp
from routes.economia import economia_bp
from routes.produccion import produccion_bp
from routes.detalle_produccion import detalle_produccion_bp
